(setq org-caldav-url "https://www.google.com/calendar/dav")
(setq org-caldav-calendar-id "vnon5391fcnpu4s03jfrlptfjc@group.calendar.google.com")
(setq org-caldav-inbox (concat org-directory "/professional-cal.org"))
(setq org-icalendar-timezone "America/Buenos_Aires")
(setq org-caldav-files "")
